### ISSUE TITLE
compatibility with 0.9.8

### ISSUE THREAD

**Issue by AIasd** [dianchen96/LearningByCheating#13]
Hi! I just wonder if the code will also work in carla 0.9.8 or is it relatively easy to extend it for that?

Thanks!

**Comment by bradyz** [comment]
I think it would be take maybe an afternoon -
We also have an upcoming release this week for the Carla challenge that uses 0.9.8 if you are interested

**Comment by AIasd** [comment]
Look forward to it! Will it be also in this git repo?
