### ISSUE TITLE
Flickering bug in using data_collector.py to get semantic segmentation

### ISSUE THREAD

**Issue by Jimuyangz** [dianchen96/LearningByCheating#21]
Hi,
I try to use your ''data_collector.py'' to collect some data with semantic segmentation ground truth by adding the semantic segmentation camera in ''bird_view/utils/carla_utils.py''. Among the good semantic segmentation images (the first figure), there are always some flickering frames whose segmentation is wrong (the second figure). I checked the raw data from the semantic segmentation camera. It seems in those flickering frames the size of the raw data is much smaller than the regular size and there are 'nan' in the the raw data before converted to 'uint8'.
*Correct semantic segmentation:*
![346seg](https://user-images.githubusercontent.com/26457246/81530915-ca008880-932f-11ea-9be5-df3ee92cc52d.jpg)
*Wrong semantic segmentation:*
![347seg](https://user-images.githubusercontent.com/26457246/81530928-cf5dd300-932f-11ea-9c2c-4947c51533ee.jpg)

I wonder if anyone ever has such problems and I would be grateful if anyone would help me with it.

**Comment by dotchen** [comment]
Please consider posting this in the original CARLA repo.
