### ISSUE TITLE
Is the training and testing data for published model available?

### ISSUE THREAD

**Issue by FitashUlHaq** [dianchen96/LearningByCheating#22]
Hi 

I am trying to replicate the results, if you can provide me any guideline regarding the actual training and test data for the published model that will help me a lot.

Waiting for any guideline

Many thanks

**Comment by dotchen** [comment]
Hi,

You can use the provided data collector script in this repo to collect your own training data, and follow the instructions to train. This should allow you to reproduce the numbers with little PID tuning.
