### ISSUE TITLE
Weird cases where autopilot would ignore the red light

### ISSUE THREAD

**Issue by peiyunh** [dianchen96/LearningByCheating#28]
I found some weird cases where autopilot would ignore the red light, which was also mentioned in another thread: https://github.com/dianchen96/LearningByCheating/issues/2#issuecomment-668961125. 

I am posting it here in case others are curious. Below are some videos. Interestingly, it looks like all cases happen at the same intersection. I am wondering if this is the one traffic light @dianchen96 mentioned about in https://github.com/dianchen96/LearningByCheating/issues/2#issuecomment-669259368. 

![NoCrashTown01_v5_seed0_s129_t88_w6](https://user-images.githubusercontent.com/10396605/89449898-bc3c8280-d727-11ea-8608-62074196a688.gif)

![NoCrashTown01_v6_seed0_s191_t114_w14](https://user-images.githubusercontent.com/10396605/89449922-c494bd80-d727-11ea-9212-f0f8c8cd4f3f.gif)

![NoCrashTown01_v8_seed0_s191_t114_w14](https://user-images.githubusercontent.com/10396605/89449938-c9f20800-d727-11ea-8265-2065f0c674af.gif)

**Comment by dotchen** [comment]
Were you able to reproduce the numbers though? @peiyunh 

Also please consider posting this to the original CARLA repo, if you found this still not fixed in the later versions. Thanks!

**Comment by peiyunh** [comment]
Yeah! I was able to reproduce the autopilot's numbers. These are just cases that I find intriguing. 

Great suggestion. I will test later versions when I get a chance. Will close the issue for now. 

Thanks.
