### ISSUE TITLE
Is there a way to check if I installed the egg file correctly?

### ISSUE THREAD

**Issue by peiyunh** [dianchen96/LearningByCheating#29]
I was browsing the visualizations you shared via Google drive. I noticed pedestrians cross the streets quite often. It struck me that I have never seen this happening when I run simulation locally. I suspect it could be that I did not install the egg file correctly. I know you have mentioned fixes you've done regarding pedestrians. I wonder if there is a way to check if I have installed the patched version correctly. 

Thanks a lot. I really appreciate the help!

**Comment by dotchen** [comment]
If none of the pedestrians are crossing my guess is that the navmesh file is not setup correctly? 

Make sure you have http://www.cs.utexas.edu/~dchen/lbc_release/navmesh/Town01.bin and http://www.cs.utexas.edu/~dchen/lbc_release/navmesh/Town02.bin downloaded and replacing the original files.

**Comment by peiyunh** [comment]
Great catch! I don't know how I missed that, but pedestrians now are able to cross streets after I replaced the navmesh file. Thanks!!

**Comment by peiyunh** [comment]
Btw, if I want to run CARLA offscreen via docker with the new navmesh files, I will have to rebuild the docker image, right?

**Comment by dotchen** [comment]
No it should work out of the box. The CARLA docker is independent of the CARLA binary.

**Comment by peiyunh** [comment]
I was using the official docker image for CARLA 0.9.6, which has everything (including navmesh files) bundled and is immutable. It turns out I have to build a docker image after replacing those navmesh files and run the new docker image to see pedestrians crossing. Thanks for the help!

**Comment by dotchen** [comment]
You shouldn't need to because I was using the docker image as well on the cluster. Inside docker image you can still run the modified CARLA. (You dont have to run the CARLA that comes with the docker image, you can still launch the one on your fs)
