### ISSUE TITLE
RPC connection error

### ISSUE THREAD

**Issue by Rookie-81** [dianchen96/LearningByCheating#36]
Hello everyone when i ever i try to execute `CUDA_VISIBLE_DEVICES="0" python benchmark_agent.py --suite=town2 --model-path=ckpts/image/model-10.th --show`

this error shows up

world = client.get_world()
RuntimeError: rpc::rpc_error during call in function version

any help will be appreciated.

**Comment by Rookie-81** [comment]
Closing because i've found the solution
1)i did pip3 uninstall carla
2) had to find a workaround to get easy_install to work and installed the provided egg
Thank you, and awesome work!

**Comment by Kin-Zhang** [comment]
![image](https://user-images.githubusercontent.com/35365764/121352343-56c8ac00-c95f-11eb-9f0f-3477764bc135.png)
I think I maybe have the same problem but different error or can say that the client cannot get the world.
But I tried the 
uninstall and install provided egg ... still cannot work.

**Comment by Kin-Zhang** [comment]
> ![image](https://user-images.githubusercontent.com/35365764/121352343-56c8ac00-c95f-11eb-9f0f-3477764bc135.png)
> I think I maybe have the same problem but different error or can say that the client cannot get the world.
> But I tried the
> uninstall and install provided egg ... still cannot work.

OK I finally got the way, you cannot run the benchmark_agent first, when I run other file like data_collection.py it's okay. Just for other people who may meet this question.
