### ISSUE TITLE
data_collector.py saves files as data.mdb and lock.mdb and not .lmdb

### ISSUE THREAD

**Issue by Jidenna** [dianchen96/LearningByCheating#37]
I tried runnung 

`python data_collector.py --dataset_path=dataset`

but the output I get on the dataset folder ends up being a data.mdb and lock.mdb file rather than the .lmdb in the train and val folder as highlighted on your README.md. What am I doing wrong? 

How do I get the files to be a .lmdb file type in a train and val folder needed to train the privileged agent?

**Comment by dotchen** [comment]
lmdb files are saved as the lock and data file as the format.

**Comment by Jidenna** [comment]
What does that mean? 

After runnning the data_collector.py script successful. I tried to run the cd training
python train_image_phase0.py --dataset_path=[DATA PATH] --log_dir=[LOG DIR] --pretrained --teacher_path=[TEACHER PATH]
